name: Generate updated documentation

on:
  push:
    branches: [ main ]
    
permissions: 
  contents: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run compile-typedoc
    - run: npm run generate-docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: build-docs-gh-pages
        folder: dist/docs
